version: 1.0.{build}
skip_tags: true
stack: node 9
skip_commits:
  message: /chore/
image: 
- Ubuntu
- Visual Studio 2017
init:
    - cmd: git config --global core.autocrlf true
install:
    - sh: wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
    - sh: sudo dpkg -i packages-microsoft-prod.deb
    - sh: sudo apt-get -y install apt-transport-https
    - sh: sudo apt-get update
    - sh: sudo apt-get -y install dotnet-sdk-2.2
    - sh: sudo apt -y install nuget
    - sh: nuget install GitVersion.CommandLine -ExcludeVersion
    - sh: mono GitVersion.CommandLine/tools/GitVersion.exe /l console /output buildserver
    - ps: if ($isWindows) { ./dotnet-install.ps1 -Version 2.2.100 }
    - cmd: gitversion /l console /output buildserver
    - cmd: nuget install ReportGenerator -ExcludeVersion
    - nuget install secure-file -ExcludeVersion
    - cmd: secure-file\tools\secure-file -decrypt test\testsettings.json.enc -secret %decrypt_secret%
    - cmd: secure-file\tools\secure-file -decrypt test\identityfirestore.json.enc -secret %decrypt_secret%
    - sh: mono secure-file/tools/secure-file.exe -decrypt test/testsettings.json.enc -secret $decrypt_secret
    - sh: mono secure-file/tools/secure-file.exe -decrypt test/identityfirestore.json.enc -secret $decrypt_secret
    - ps: ./appveyorinit.ps1
build_script:
    - ps: ./build.ps1
test_script:
    - cmd: publish.cmd
artifacts:
    - path: artifacts/**/*.nupkg
      name: nuget    
deploy:
    - provider: NuGet
      api_key:
        secure: 23wPDdRicGt2vZuJ8vd9TRBKmqjHkx5WjzZmKvyxd5j0fNPedjUScRTj/rT0ObJa
      on:
        branch:
            - /preview\/*/ 
            - /release\/*/
    - provider: GitHub
      auth_token: $(GH_TOKEN)
      draft: true
      prerelease: false
      release: $(APPVEYOR_BUILD_VERSION)
      on:
        branch: 
            - /preview\/*/ 
        CI_WINDOWS: true
for:
-
  branches:
    only:
      - master
  on_success:
    - cmd: git config --global credential.helper store 
    - ps: if ($isWindows) { Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:GH_TOKEN):x-oauth-basic@github.com`n" }
    - cmd: IF EXIST coverage\docs ( git config --global user.email "aguacongas@gmail.com" )
    - cmd: IF EXIST coverage\docs ( git config --global user.name "Olivier Lefebvre" )
    - cmd: IF EXIST coverage\docs ( git stash )
    - cmd: IF EXIST coverage\docs ( git checkout gh-pages )
    - cmd: IF EXIST latest ( rmdir /S /Q latest )
    - cmd: IF EXIST coverage\docs ( move coverage\docs latest )
    - cmd: IF EXIST latest ( git add latest )
    - cmd: IF EXIST latest ( git commit latest -m "Appveyor build succed %APPVEYOR_BUILD_NUMBER%" )
    - cmd: IF EXIST latest ( git push )
-
  branches:
    only:
      - /release\/*/
  on_success:
      - cmd: semantic-release -b %APPVEYOR_REPO_BRANCH%
      - cmd: git config --global credential.helper store
      - ps: if ($isWindows) { Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:GH_TOKEN):x-oauth-basic@github.com`n" }
      - cmd: git config --global user.email "aguacongas@gmail.com"
      - cmd: git config --global user.name "Olivier Lefebvre"
      - cmd: git checkout gh-pages
      - cmd: git stash
      - cmd: mkdir %APPVEYOR_BUILD_VERSION%
      - cmd: move coverage\docs %APPVEYOR_BUILD_VERSION%
      - cmd: git add %APPVEYOR_BUILD_VERSION%
      - cmd: git commit %APPVEYOR_BUILD_VERSION% -m "Appveyor build succed %APPVEYOR_BUILD_NUMBER%"
      - cmd: git push
-
  branches:
    except:
      - /release\/*/
