version: 1.0.{build}
image: Visual Studio 2017
environment:
  access_token:
    secure: yQcU3EbE3/jaIhwn6e+n76xzcQ+tGXXdIZAmA3Z8ssj5IEYPehthJkLYhhNEmw21
  FirebaseOptions:DatabaseUrl:
    secure: 2qGe9esmMdZbcKA/cWYZ8vbQpX8P1FbS4bynR0m6gBS4APskJ+a8rnleo/8UgfPC
  EmailPasswordOptions:ApiKey:
    secure: CgnX5RPcI4Wq1hyLKIh+5DaEl6wfV/Mdo6J8u3mW0A4iVBBXpPblFpp5vh0DUauI
  EmailPasswordOptions:Email:
    secure: M+wRwy+l/01DvVvmy0Th96FLiwzNnwK3Sp1YMvMnUns=
  EmailPasswordOptions:Password:
    secure: h7zhWIG5sQBVM6loU77ClQ==
  AuthTokenOptions:project_id:
    secure: gE6/37a4VG4TdhewmnfFTIZHTzue+4h4fe/3s4YfdLo=
  AuthTokenOptions:private_key_id:
    secure: heNPEQDaV8Zztg/9IdO8uftdRig8wf72Up33RgTzQFcZRw29Kh6WgaIwKP52DypD
  AuthTokenOptions:private_key:
    secure: lYWao9RdvrvPB2yOgaz9tH2inTmp3mZdp8YPxSwF6CeQuPkQZn7P3OMFGPqY+aHtNrUDtv1ZDTwqYmpSDVcCL0C0fpIoUu6eDKIE1vdWpPdoUB0B6VkCmBuNxojNHGlVI6wa+obh9C/Ik6bAyOeN1q16hNXX7QlDFON48pnXDMELUiANbB30+VNKTFVMrn8H3g4E2hr0+mK1yb/PAtKrZcmHM1JbOuA7YQiZ9raGdS0GR5XWuBtGlopto7eTgPUBCynpzfJ+ziT0MhIGpwBalNRCgOR2mXPU4TciYNxJoVYeHSotkri/BTIeDVdCC3ifDuDR/lOvMKCjprNWFQ11LYYqDP68NzXLvjm/ix9Tc0YX9A1tSo32HmchlAAjPjEju/Gh8oaS7W2b5C2EjTbwAvWkO9H4cGxTa8MEOwqHzbckMlo+tUO0q2h2xE2J2At0K3Weze3GJ6PHuZTdYoNxagPX7/YWt8b69tqXx9leDtwsCZ5yF53hL1zzIyEPhJw6gezbkJlYgZst2RjRXs+xN4aVdMYQ8DTNtKQz9RJNN3LYO/3jQWJhJHSRM/cR175L9AH+SzFjsfFITcP1cfhAGAjeS+rRAYmKkQqm5+2Azv22q+DVWZ3tJKrqJYZNNrg6UTR4JtF7mXHuh09dL449tAOU63/88VZrkKzmYY+A8KDLNIlag/xqIzKW3GpsdT4EsPjW++eJEdPI9J2B6BsYHv3Fe7yidePcRVdF3Kvu9BHWRIYyZIzb1kR55gw7dDQsfdVgl5b+LAZjfAEXJ3C/hi7VPknvnWtUzqIX1b7yj0svfuM3PiyKPQREKPS1Sv955HhIf8uxwqyaRTG0Or5rWj+d6G9kQncZO2PAL6TmVRM+bIDOv2n0E5r0o7IfD716p5sr9fGM9fcix4Myfu1jGkR8EpgoumUvT6PQqAy8B0ojjOXe6bWafz0rea0wO3+maK2BiJ3e0f5Vm/Ze7RWV3PFCQ5SRmYyeBonosb6bwpxtlBPuOROlF2PcetsBjYZxIZqjvYyHee1Hdt3FWzAKo/mAqBm7ho3E92qOLN2meWKfB6FdCLgtU95HaFMiPqighQ+yzp1fNIoZYEgYGflXjh6DwpPLMs9RRmJxR+n4PZW4pz1oCBP9ekZKBpOL1mqZpAoRmlaTLi1XvyUf51LGfNhEgs+B3gr/nw5U8Wy4eW+1/Er2tYpXklpv5lRzYQBS1UHtsQNSfVd9Fvcm0ND8TBBhO7xtZaxi50amUKASGVSfvefa+wUCFLQiP84CDGEAcBHoLWsiZ7j7IHrrLXCCCQWo5z4CYkSzoz6dgYra9rkm4ZVK1kpfYhUnIiW7Q4kfEgFePb9bvhfOSI6HL0wacybDEDA6ZQnk4jcLa4zQ80KIowo6B9QI0dk7qMWLWrQwtjmx4+fy4TjI9rUW6NCi980SmoaFFPUYvcuz7MadlbpQnSYiNlMdsZVxKvl9yTG5MyY/2lLkXexrZG6yahMY8qrlkoaAZ7i6cQksMFxH3UJsM7MNmO2sVYBI71l4CitqLl68phfWX2Hsa8G48rwx2C9dEF5ng9/D+HtPbzLLOlC7FNEgvAh4bTjMx0iTy2L1it0lHPYJ4m6Vhia9wQioOJn+shQo7zTXpeyPFK+jNREOykOQXPQguoFb/OWLLXQQ52X3cikWpZ/pgjb7PaPGYXK+Hom89uM1WIVfx7p+uO9bHXYTWImuv0hgxqd6KczTyBxgX+To1qEB+dP3xAHi/YsKPE3JfHXEAo9J3krp36AlcbBhsCmlWtYlH7X3Qcp9P6l6esdjgfJPLd4Pa4S7pFq2IaknPPRRnrbxuAQfZcpAhMhWopC04Fe60fZhSvwUeh99Qow/s6KKCJlPv4AOY9Ephwh1GRiXz9AJ8oZxWRyBZSMSDwB5UiDYYAbn/IyHmL1GsWlDyGJeyKC7+4+Zm93DtvUKTs4ZIf6yAlwnz10UcF/n9ULp1uodFSe5EXVbD/StmA9N6+Dfk3XR3gpgMgOZxsRcR192ZTvuDaLwA9zIbIIUn9MknaD/2kExMlLiABJm+eMrVrBVGt5SicpazzQ433TkTcvsJp4PzdayIQGcdn2+3ArvwqtP+PBbyOMmcOCbP77j4aYU1lgcB7aG//twa2+bLVw7v+W4220JfRf9dIXuoPigUaXyqu1TC5doabwot5KLfmLnD2BDes/K3kJYAlJk/B+FGlqBBrfIJ7ALXrly9Ta8+fo0WEcxKTR3hQBqLF7wlxQ6nA9nuW7f+MiwRUTKYb07FLWKf/OUeAU=
  AuthTokenOptions:client_email:
    secure: kTyppzJ2/ZxaGTdrdYTHXMMRJgOJ82mJvPS6YzV2xB2s4bPC3nSQ1YUA1mfkb5zmJTkBRWlTMniJDmx8pRTmwtNJOF64UIf+wnVH0CnpQC8=
  AuthTokenOptions:client_id:
    secure: PMLy88L3M2YQyiYbIPN6z0imAgOXFMzqbZZPaRNAc/w=
init:
    - cmd: git config --global core.autocrlf true
install:
    - cmd: gitversion /l console /output buildserver
    - cmd: dotnet restore
build_script:
    - cmd: msbuild src\Aguacongas.Firebase /t:Pack /p:Version="%GITVERSION_NuGetVersion%" /p:FileVersion="%GITVERSION_AssemblySemVer%" /p:AssemblyVersion="%GITVERSION_AssemblySemVer%" /p:Configuration=Release
    - cmd: msbuild src\Aguacongas.Identity.Firebase /t:Pack /p:Version="%GITVERSION_NuGetVersion%" /p:FileVersion="%GITVERSION_AssemblySemVer%" /p:AssemblyVersion="%GITVERSION_AssemblySemVer%" /p:Configuration=Release
test_script:
    - cmd: cover.cmd
artifacts:
    - path: src/**/*.nupkg
      name: nuget    
on_success:
    - git config --global credential.helper store
    - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
    - git config --global user.email "aguacongas@gmail.com"
    - git config --global user.name "Aguacongas"
    - git checkout master
    - rmdir /S /Q docs\latest
    - move coverage\docs docs\latest
    - git add docs\latest
    - git commit docs\latest -m "Appveyor build succed %APPVEYOR_BUILD_NUMBER%"
    - git push
deploy:
    - provider: NuGet
      api_key:
        secure: 23wPDdRicGt2vZuJ8vd9TRBKmqjHkx5WjzZmKvyxd5j0fNPedjUScRTj/rT0ObJa
      on:
        branch: 
            - develop
            - master
            - /release*/