version: 1.0.{build}
skip_tags: true
stack: node 10
skip_commits:
  message: /chore(release)/
branches:
  only:
  - master
  - /preview\/*/
  - /release\/*/
image: 
- Ubuntu
- Visual Studio 2019
environment:
  GH_TOKEN:
    secure: 01BiLL1kdV7X6Y7RjFyKPYwMEQr6vEpyLsGwqnRqHpMY7AyGlPdktsUH4L5A9vR6
  access_token:
    secure: yQcU3EbE3/jaIhwn6e+n76xzcQ+tGXXdIZAmA3Z8ssj5IEYPehthJkLYhhNEmw21
  EmailPasswordOptions:ApiKey:
    secure: CgnX5RPcI4Wq1hyLKIh+5DaEl6wfV/Mdo6J8u3mW0A4iVBBXpPblFpp5vh0DUauI
  EmailPasswordOptions:Email:
    secure: M+wRwy+l/01DvVvmy0Th96FLiwzNnwK3Sp1YMvMnUns=
  EmailPasswordOptions:Password:
    secure: h7zhWIG5sQBVM6loU77ClQ==
  decrypt_secret:
    secure: BDKOW5teXcJUwLqekbf6VQ==
  donetsdk: 6.0.100
init:
    - cmd: git config --global core.autocrlf true
install:
    - ps: if ($isWindows) { Install-Product node '' }
    - sh: wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
    - sh: sudo dpkg -i packages-microsoft-prod.deb
    - sh: sudo apt-get update
    - sh: sudo apt-get -y install apt-transport-https
    - sh: sudo chmod +x ./dotnet-install.sh
    - sh: sudo ./dotnet-install.sh -Channel Current -Version $donetsdk -InstallDir ./dotnetsdk -NoPath
    - sh: export PATH=/home/appveyor/projects/identity-firebase/dotnetsdk:$PATH
    - sh: sudo apt -y install nuget
    - ps: if ($isWindows) { ./dotnet-install.ps1 -Version $env:donetsdk }
    - ps: dotnet tool install --global GitVersion.Tool
    - ps: dotnet gitversion /l console /output buildserver
    - ps: dotnet tool install --global dotnet-sonarscanner
    - cmd: nuget install ReportGenerator -ExcludeVersion
    - nuget install secure-file -ExcludeVersion
    - cmd: secure-file\tools\secure-file -decrypt test\testsettings.json.enc -secret %decrypt_secret%
    - cmd: secure-file\tools\secure-file -decrypt test\identityfirestore.json.enc -secret %decrypt_secret%
    - sh: mono secure-file/tools/secure-file.exe -decrypt test/testsettings.json.enc -secret $decrypt_secret
    - sh: mono secure-file/tools/secure-file.exe -decrypt test/identityfirestore.json.enc -secret $decrypt_secret
    - ps: ./appveyorinit.ps1
    - cmd: set JAVA_HOME=C:\Program Files\Java\jdk14
    - cmd: set PATH=%JAVA_HOME%\bin;%PATH%
build_script:
    - ps: ./build.ps1
test_script:
    - cmd: publish.cmd
artifacts:
    - path: artifacts/**/*.nupkg
      name: nuget    
deploy:
    - provider: NuGet
      api_key:
        secure: bvkKhXIKsDM1ThfcWTbuusND0sOBiDoJGOoD2fYijGoj4C9xx22QKfR7Y9q+j7eX
      on:
        branch:
        - /preview\/*/ 
        - /release\/*/
        CI_WINDOWS: true
    - provider: GitHub
      auth_token: $(GH_TOKEN)
      draft: true
      prerelease: true
      release: $(NextVersion)
      on:
        branch: 
            - /preview\/*/ 
        CI_WINDOWS: true
    - provider: GitHub
      auth_token: $(GH_TOKEN)
      draft: true
      release: $(NextVersion)
      on:
        branch: 
          - /release\/*/
        CI_WINDOWS: true
for:
-
  branches:
    only:
      - /release\/*/
  on_success:
      - cmd: semantic-release -b %APPVEYOR_REPO_BRANCH%
