version: 1.0.{build}
skip_tags: true
stack: node 9
skip_commits:
  message: /\[chore\]/
branches:
  only:
  - master
  - /preview*/             
  - /release*/
image: 
- Ubuntu
- Visual Studio 2017
environment:
  GH_TOKEN:
    secure: 01BiLL1kdV7X6Y7RjFyKPYwMEQr6vEpyLsGwqnRqHpMY7AyGlPdktsUH4L5A9vR6
  access_token:
    secure: yQcU3EbE3/jaIhwn6e+n76xzcQ+tGXXdIZAmA3Z8ssj5IEYPehthJkLYhhNEmw21
  FirebaseOptions:DatabaseUrl:
    secure: 2qGe9esmMdZbcKA/cWYZ8vbQpX8P1FbS4bynR0m6gBS4APskJ+a8rnleo/8UgfPC
  EmailPasswordOptions:ApiKey:
    secure: CgnX5RPcI4Wq1hyLKIh+5DaEl6wfV/Mdo6J8u3mW0A4iVBBXpPblFpp5vh0DUauI
  EmailPasswordOptions:Email:
    secure: M+wRwy+l/01DvVvmy0Th96FLiwzNnwK3Sp1YMvMnUns=
  EmailPasswordOptions:Password:
    secure: h7zhWIG5sQBVM6loU77ClQ==
  AuthTokenOptions:project_id:
    secure: gE6/37a4VG4TdhewmnfFTIZHTzue+4h4fe/3s4YfdLo=
  AuthTokenOptions:private_key_id:
    secure: heNPEQDaV8Zztg/9IdO8uftdRig8wf72Up33RgTzQFcZRw29Kh6WgaIwKP52DypD
  AuthTokenOptions:client_email:
    secure: kTyppzJ2/ZxaGTdrdYTHXMMRJgOJ82mJvPS6YzV2xB2s4bPC3nSQ1YUA1mfkb5zmJTkBRWlTMniJDmx8pRTmwtNJOF64UIf+wnVH0CnpQC8=
  AuthTokenOptions:client_id:
    secure: PMLy88L3M2YQyiYbIPN6z0imAgOXFMzqbZZPaRNAc/w=
  decrypt_secret:
    secure: BDKOW5teXcJUwLqekbf6VQ==
init:
    - cmd: git config --global core.autocrlf true
install:
    - sh: wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
    - sh: sudo dpkg -i packages-microsoft-prod.deb
    - sh: sudo apt-get -y install apt-transport-https
    - sh: sudo apt-get update
    - sh: sudo apt-get -y install dotnet-sdk-2.2
    - sh: sudo apt -y install nuget
    - sh: nuget install GitVersion.CommandLine -ExcludeVersion
    - sh: mono GitVersion.CommandLine/tools/GitVersion.exe /l console /output buildserver
    - ps: if ($isWindows) { ./dotnet-install.ps1 -Version 2.2.100 }
    - cmd: gitversion /l console /output buildserver
    - cmd: nuget install ReportGenerator -ExcludeVersion
    - nuget install secure-file -ExcludeVersion
    - cmd: secure-file\tools\secure-file -decrypt test\testsettings.json.enc -secret %decrypt_secret%
    - cmd: secure-file\tools\secure-file -decrypt test\identityfirestore.json.enc -secret %decrypt_secret%
    - sh: mono secure-file/tools/secure-file.exe -decrypt test/testsettings.json.enc -secret $decrypt_secret
    - sh: mono secure-file/tools/secure-file.exe -decrypt test/identityfirestore.json.enc -secret $decrypt_secret
    - ps: ./appveyorinit.ps1
build_script:
- ps: ./build.ps1
test_script:
- cmd: publish.cmd
artifacts:
    - path: artifacts/**/*.nupkg
      name: nuget    
on_success:
    - cmd: git config --global credential.helper store
    - ps: if ($isWindows) { Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:GH_TOKEN):x-oauth-basic@github.com`n" }
    - cmd: git config --global user.email "aguacongas@gmail.com"
    - cmd: git config --global user.name "Olivier Lefebvre"
    - cmd: git stash
    - cmd: git checkout gh-pages
    - cmd: IF EXIST latest ( rmdir /S /Q latest )
    - cmd: move coverage\docs latest
    - cmd: git add latest
    - cmd: git commit latest -m "Appveyor build succed %APPVEYOR_BUILD_NUMBER%"
    - cmd: git push
deploy:
    - provider: NuGet
      api_key:
        secure: 23wPDdRicGt2vZuJ8vd9TRBKmqjHkx5WjzZmKvyxd5j0fNPedjUScRTj/rT0ObJa
      on:
        branch:
            - /preview*/ 
            - /release*/
    - provider: GitHub
      auth_token: $(GH_TOKEN)
      draft: true
      prerelease: false
      release: $(APPVEYOR_BUILD_VERSION)
      on:
        branch: 
            - /preview*/ 
            - /release*/
        CI_WINDOWS: true
for:
-
  branches:
    only:
      - /release*/
  on_success:
      - cmd: git config --global credential.helper store
      - ps: if ($isWindows) { Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:GH_TOKEN):x-oauth-basic@github.com`n" }
      - cmd: git config --global user.email "aguacongas@gmail.com"
      - cmd: git config --global user.name "Olivier Lefebvre"
      - cmd: git checkout gh-pages
      - cmd: git stash
      - cmd: mkdir %APPVEYOR_BUILD_VERSION%
      - cmd: move coverage\docs %APPVEYOR_BUILD_VERSION%
      - cmd: git add %APPVEYOR_BUILD_VERSION%
      - cmd: git commit %APPVEYOR_BUILD_VERSION% -m "Appveyor build succed %APPVEYOR_BUILD_NUMBER%"
      - cmd: git push
-
  branches:
    except:
      - /release*/
