version: 1.0.{build}
image: Visual Studio 2017
environment:
  access_token:
    secure: yQcU3EbE3/jaIhwn6e+n76xzcQ+tGXXdIZAmA3Z8ssj5IEYPehthJkLYhhNEmw21
  FirebaseOptions:DatabaseUrl:
    secure: 2qGe9esmMdZbcKA/cWYZ8vbQpX8P1FbS4bynR0m6gBS4APskJ+a8rnleo/8UgfPC
  EmailPasswordOptions:ApiKey:
    secure: CgnX5RPcI4Wq1hyLKIh+5DaEl6wfV/Mdo6J8u3mW0A4iVBBXpPblFpp5vh0DUauI
  EmailPasswordOptions:Email:
    secure: M+wRwy+l/01DvVvmy0Th96FLiwzNnwK3Sp1YMvMnUns=
  EmailPasswordOptions:Password:
    secure: h7zhWIG5sQBVM6loU77ClQ==
  AuthTokenOptions:project_id:
    secure: gE6/37a4VG4TdhewmnfFTIZHTzue+4h4fe/3s4YfdLo=
  AuthTokenOptions:private_key_id:
    secure: heNPEQDaV8Zztg/9IdO8uftdRig8wf72Up33RgTzQFcZRw29Kh6WgaIwKP52DypD
  AuthTokenOptions:client_email:
    secure: kTyppzJ2/ZxaGTdrdYTHXMMRJgOJ82mJvPS6YzV2xB2s4bPC3nSQ1YUA1mfkb5zmJTkBRWlTMniJDmx8pRTmwtNJOF64UIf+wnVH0CnpQC8=
  AuthTokenOptions:client_id:
    secure: PMLy88L3M2YQyiYbIPN6z0imAgOXFMzqbZZPaRNAc/w=
  decrypt_secret:
    secure: WmQGkRXx/KBqXzl928plapnOEcBSdSxW3jEoR3Esoic=
init:
    - cmd: git config --global core.autocrlf true
install:
    - cmd: gitversion /l console /output buildserver
    - cmd: nuget install secure-file -ExcludeVersion
    - cmd: secure-file\tools\secure-file -decrypt test\testsettings.json.enc -secret %decrypt_secret%
    - cmd: dotnet restore
build_script:
    - cmd: msbuild src\Aguacongas.Firebase /t:Pack /p:Version="%GITVERSION_NuGetVersion%" /p:FileVersion="%GITVERSION_AssemblySemVer%" /p:AssemblyVersion="%GITVERSION_AssemblySemVer%" /p:Configuration=Release
    - cmd: msbuild src\Aguacongas.Identity.Firebase /t:Pack /p:Version="%GITVERSION_NuGetVersion%" /p:FileVersion="%GITVERSION_AssemblySemVer%" /p:AssemblyVersion="%GITVERSION_AssemblySemVer%" /p:Configuration=Release
test_script:
    - cmd: cover.cmd
artifacts:
    - path: src/**/*.nupkg
      name: nuget    
on_success:
    - git config --global credential.helper store
    - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
    - git config --global user.email "aguacongas@gmail.com"
    - git config --global user.name "Aguacongas"
    - git checkout master
    - rmdir /S /Q docs\latest
    - move coverage\docs docs\latest
    - git add docs\latest
    - git commit docs\latest -m "Appveyor build succed %APPVEYOR_BUILD_NUMBER%"
    - git push
deploy:
    - provider: NuGet
      api_key:
        secure: 23wPDdRicGt2vZuJ8vd9TRBKmqjHkx5WjzZmKvyxd5j0fNPedjUScRTj/rT0ObJa
      on:
        branch: 
            - master
            - /release*/
    - provider: GitHub
      auth_token:
        secure: u7qaOQsrkLqq44yS24C0eM2vRCzp1A8gZTWNmlA58TIDJGmrDXguHL9H/vww7Fg/
      draft: false
      prerelease: true
      on:
        branch: 
            - /release*/
    - provider: GitHub
      auth_token:
        secure: u7qaOQsrkLqq44yS24C0eM2vRCzp1A8gZTWNmlA58TIDJGmrDXguHL9H/vww7Fg/
      draft: false
      prerelease: true
      on:
        branch: 
            - master
for:
-
  branches:
    only:
      - master
  on_success:
    - cmd: echo "skip coverage report deploy"
-
  branches:
    except:
      - master
